version: '3'

services:
  nginx:
      image: nginx:1.23.2
      container_name: nginx
      restart: unless-stopped
      ports:
        - "8082:80"
      volumes:
        - ${HTML_DIR}:/usr/share/nginx/html
        - ./default.conf:/etc/nginx/conf.d/default.conf


  cloudflared:
      image: cloudflare/cloudflared:2022.12.0-amd64
      container_name: cloudflared-use-nginx
      restart: unless-stopped
      command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
      volumes:
        - ./cloudflared-data:/data
      
  
